# Generated by Django 5.0.4 on 2024-05-07 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_users_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Staffs',
        ),
    ]
