# Generated by Django 5.0.4 on 2024-05-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_users_staffs'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='address',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
